# Generated by Django 4.0.4 on 2023-06-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='password',
            field=models.TextField(default=1234, max_length=10),
            preserve_default=False,
        ),
    ]
