# Generated by Django 4.0.4 on 2023-06-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_employee_emailaccount_owner'),
        ('computer', '0002_computer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='model',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='computer',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='computer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee'),
        ),
    ]
