# Generated by Django 4.0.4 on 2023-06-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_alter_computer_model_alter_computer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
