# Generated by Django 4.0.4 on 2023-06-20 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_employee_emailaccount_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
