# Generated by Django 4.0.4 on 2023-06-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_emailaccount_owner_alter_emailaccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='name',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
