# Generated by Django 4.0.4 on 2023-06-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_emailaccount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
